const ClockItemActionTypes = {
    SET_CLOCK_ITEMS: 'SET_CLOCK_ITEMS',
    SET_CLOCK_ITEMS_BY_DATE: 'SET_CLOCK_ITEMS_BY_DATE',
    ADD_CLOCK_ITEM: 'ADD_CLOCK_ITEM',
    UPDATE_CLOCK_ITEMS: 'UPDATE_CLOCK_ITEMS',
    DELETE_CLOCK_ITEM: 'DELETE_CLOCK_ITEM',
    SIGNOUT_USER: 'SIGNOUT_USER'
};

export default ClockItemActionTypes;